blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using shuffledns
    url: https://github.com/mohammadanaraki/shuffledns/discussions/categories/q-a
    about: Ask a question or request support for using shuffledns

  - name: Share idea / feature to discuss for shuffledns
    url: https://github.com/mohammadanaraki/shuffledns/discussions/categories/ideas
    about: Share idea / feature to discuss for shuffledns

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication
